### ISSUE TITLE
Add a security policy

### ISSUE THREAD

**Issue by JamieSlome** [codeverland/codever#77]
Hey there!

I belong to an open source security research community, and a member (@aravindd007) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by adi-matei** [comment]
Create a security.md file. Thank you for your suggestion.

**Comment by JamieSlome** [comment]
@adi-matei - thanks for your response! ⚡ 

You should have received an e-mail about 4 hours ago. Otherwise, you can view the report directly here:

https://huntr.dev/bounties/b083f22d-6ea5-4cfc-bd29-55734542bcc7/

it is private and only accessible to maintainers with repository push permissions 👍
